import type { CompilerIR } from '../types.js'

const toSnake = (value: string): string => value.replace(/[^a-zA-Z0-9]+/g, '_').toLowerCase()

const toCStringLiteral = (value: string): string => {
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('\n', '\\n')

  return `"${escaped}"`
}

export const emitCSource = (ir: CompilerIR): string => {
  const fnSuffix = toSnake(ir.componentSlug)
  const htmlLiteral = toCStringLiteral(ir.html)
  const statesComment = ir.states.length > 0
    ? ir.states.map((state) => ` * - ${state.stateId}`).join('\n')
    : ' * - (none)'

  return `#include <stddef.h>

/*
 * Auto-generated by @ccss/compiler
 * Component: ${ir.componentName}
 * GeneratedAt: ${ir.generatedAt}
 * State IDs:
${statesComment}
 */
const char* ccss_render_${fnSuffix}(void) {
  return ${htmlLiteral};
}
`
}
