import type { CompilerIR } from '../types.js'

const escapeCssId = (value: string): string => (
  value
    .replaceAll(':', '\\:')
    .replaceAll('.', '\\.')
)

export const emitCssSource = (ir: CompilerIR): string => {
  const lines: string[] = [
    '/* Auto-generated by @ccss/compiler */',
    `/* Component: ${ir.componentName} */`,
    '',
    `#${ir.domRoots.uiRootId} {`,
    '  position: relative;',
    '}',
    '',
    `#${ir.domRoots.gameRootId} {`,
    '  isolation: isolate;',
    '}',
    '',
    '.ccss-state-input {',
    '  position: absolute;',
    '  opacity: 0;',
    '  pointer-events: none;',
    '}',
    '',
  ]

  for (const state of ir.states) {
    const escapedStateId = escapeCssId(state.stateId)
    lines.push(
      `[data-ccss-state="${state.stateId}"] {`,
      '  display: none;',
      '}',
      `#${escapedStateId}:checked ~ [data-ccss-state="${state.stateId}"] {`,
      '  display: block;',
      '}',
      '',
    )
  }

  return `${lines.join('\n')}\n`
}
