name: Greetings
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: '初めてのIssue作成ありがとうございます！確認まで少々お待ちください。'
          pr_message: '初めてのPull Requestありがとうございます！レビューまで少々お待ちください。'