#include <stddef.h>

/*
 * Auto-generated by @ccss/compiler
 * Component: SamplePanel
 * GeneratedAt: 2026-03-18T02:47:14.816Z
 * State IDs:
 * - ccss:sample:sample-panel:menu-open
 * - ccss:sample:sample-panel:active-tab
 */
const char* ccss_render_sample_panel(void) {
  return "<main class=\"ccss-dashboard\"><input id=\"ccss:sample:sample-panel:active-tab\" class=\"ccss-state-input\" type=\"checkbox\"></input><input id=\"ccss:sample:sample-panel:menu-open\" type=\"checkbox\"></input><label for=\"ccss:sample:sample-panel:menu-open\">open menu</label><section><nav><button data-menu-state=\"open\" onClick=\"{{() =&gt; setMenuOpen(!menuOpen)}}\">toggle menu</button><button data-active-tab=\"{{activeTab}}\" onClick=\"{{() =&gt; setActiveTab('play')}}\">switch tab</button></nav><div class=\"ccss-dashboard-stage-card\" data-ccss-state=\"ccss:sample:sample-panel:menu-open\">dashboard panel</div><div class=\"ccss-toast\">toast area</div></section></main>";
}
